Stubbed in a temporary minimal implementation of check for updates
sillsdev/saymore pull request #189
Opened 2024-07-15 21:30 UTC by tombogle

2024-07-17 22:33 UTC, andrew-polk reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/189)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/SayMore/UI/ProjectWindow/ProjectWindow.cs` line 261 at r1](https://reviewable.io/reviews/sillsdev/saymore/189#-O21oU6F71fImd43hQtl:-O21oU6G1AHvHBPbSxw3:b8ht486) ([raw file](https://github.com/sillsdev/saymore/blob/1b35152a4ca5ebdbb0b4ac5797fd35644f4d54b8/src/SayMore/UI/ProjectWindow/ProjectWindow.cs#L261)):*
> ```Smalltalk
> 		{
> 			Analytics.Track("CheckForUpdates");
> 			MessageBox.Show("Note yet implemented. Visit software.sil.org/saymore/download to check for updated version.", ProductName);
> ```

typo: Note

But I think I would skip the first sentence. It is fairly technical language.

"Please visit software.sil.org/saymore/download to check for updated version."

You could even make it a yes/no which, if they click Yes, takes them to the site. (Who is going to type in the address?...)


<!-- Sent from Reviewable.io -->

2024-07-17 22:33 UTC, andrew-polk reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/189)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/SayMore/UI/ProjectWindow/ProjectWindow.cs` line 261 at r1](https://reviewable.io/reviews/sillsdev/saymore/189#-O21oU6F71fImd43hQtl:-O21p-Gn9UuKCVMwS_Z-:bcu0zb1) ([raw file](https://github.com/sillsdev/saymore/blob/1b35152a4ca5ebdbb0b4ac5797fd35644f4d54b8/src/SayMore/UI/ProjectWindow/ProjectWindow.cs#L261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

typo: Note

But I think I would skip the first sentence. It is fairly technical language.

"Please visit software.sil.org/saymore/download to check for updated version."

You could even make it a yes/no which, if they click Yes, takes them to the site. (Who is going to type in the address?...)
</blockquote></details>

"Please visit software.sil.org/saymore/download to check for an updated version."
(added "an")


<!-- Sent from Reviewable.io -->

2024-07-18 12:19 UTC, tombogle commented
Good thoughts. Not sure I'll even release this, but I wanted to at least stub something in as a reminder to think about it.

2025-02-03 13:37 UTC, tombogle commented
*[`src/SayMore/UI/ProjectWindow/ProjectWindow.cs` line 261 at r1](https://reviewable.io/reviews/sillsdev/saymore/189#-O21oU6F71fImd43hQtl:-OIB0VDT7hP6seJpq0bf:bo2728b) ([raw file](https://github.com/sillsdev/saymore/blob/1b35152a4ca5ebdbb0b4ac5797fd35644f4d54b8/src/SayMore/UI/ProjectWindow/ProjectWindow.cs#L261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

"Please visit software.sil.org/saymore/download to check for an updated version."
(added "an")
</blockquote></details>

That was just a temporary stub-in. You can re-review the real thing. Unfortunately, until there is a first real version published, the only way to see it in action is to temporarily change the code to look for the appcast file at a different URL. (I have done that, and it seems to work, so I'm reasonably hopeful that everything will work beautifully with the actual production URL.)


<!-- Sent from Reviewable.io -->

2025-02-03 16:40 UTC, andrew-polk requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/189)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`build/SayMore.proj` line 163 at r2](https://reviewable.io/reviews/sillsdev/saymore/189#-OIBfa0yEkXQj7kncmMh:-OIBfa0yEkXQj7kncmMi:bedt931) ([raw file](https://github.com/sillsdev/saymore/blob/44a06c5d21fbf50ec16f0f5ac0862423868db927/build/SayMore.proj#L163)):*
> ```XML
> 
> 	<FileUpdate File="$(RootDir)\output\installer\appcast.xml"
> 		Regex='DEV_VERSION_NUMBER'
> ```

Curious why you chose to prefix with DEV_
___
*[`src/SayMore/UI/ProjectWindow/ProjectWindow.cs` line 222 at r2](https://reviewable.io/reviews/sillsdev/saymore/189#-OIBfC8ZAVVl492awWaX:-OIBfC8ZAVVl492awWaY:b-vkwdvz) ([raw file](https://github.com/sillsdev/saymore/blob/44a06c5d21fbf50ec16f0f5ac0862423868db927/src/SayMore/UI/ProjectWindow/ProjectWindow.cs#L222)):*
> ```Smalltalk
> 			_viewTabGroup.SetActiveView(_viewTabGroup.Tabs[0]);
> 
> 			UpdateChecker = new Sparkle(@"https://build.palaso.org/guestAuth/repository/download/SayMore_SayMoreV36Publish/.lastSuccessful/appcast.xml",
> ```

I think you want to alias this url somehow.
But maybe I'm missing something.
Maybe we should discuss?


<!-- Sent from Reviewable.io -->

2025-02-03 19:27 UTC, tombogle commented
*[`build/SayMore.proj` line 163 at r2](https://reviewable.io/reviews/sillsdev/saymore/189#-OIBfa0yEkXQj7kncmMh:-OICGvYq6nqh57R6Ebyx:b-4u8klg) ([raw file](https://github.com/sillsdev/saymore/blob/44a06c5d21fbf50ec16f0f5ac0862423868db927/build/SayMore.proj#L163)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Curious why you chose to prefix with DEV_
</blockquote></details>

Mindless imitation of how it is done in Glyssen, which was presumably mindless imitation of HearThis.


<!-- Sent from Reviewable.io -->

2025-02-03 19:31 UTC, tombogle commented
*[`build/SayMore.proj` line 163 at r2](https://reviewable.io/reviews/sillsdev/saymore/189#-OIBfa0yEkXQj7kncmMh:-OICHfzpCrtAOBiDCaMI:b-lirfab) ([raw file](https://github.com/sillsdev/saymore/blob/44a06c5d21fbf50ec16f0f5ac0862423868db927/build/SayMore.proj#L163)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Mindless imitation of how it is done in Glyssen, which was presumably mindless imitation of HearThis.
</blockquote></details>

Also that way in FlexBridge, but for some reason in Transcelerator I saw fit to bust loose and make it just VERSION_NUMBER.


<!-- Sent from Reviewable.io -->

2025-02-03 19:56 UTC, tombogle commented
*[`src/SayMore/UI/ProjectWindow/ProjectWindow.cs` line 222 at r2](https://reviewable.io/reviews/sillsdev/saymore/189#-OIBfC8ZAVVl492awWaX:-OICN4MDAehSXYV2lWxL:babdupg) ([raw file](https://github.com/sillsdev/saymore/blob/44a06c5d21fbf50ec16f0f5ac0862423868db927/src/SayMore/UI/ProjectWindow/ProjectWindow.cs#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you want to alias this url somehow.
But maybe I'm missing something.
Maybe we should discuss?
</blockquote></details>

It's definitely hardcoded similar to this in Glyssen and HearThis. Your comment may reflect the most unfortunate reality that the URL for the production build contains an overly specific version number. I have changed the name of the build configuration to be more general. Maybe the thing to do would be to create a new build config for v. 3.7 and later.


<!-- Sent from Reviewable.io -->

2025-02-03 21:40 UTC, tombogle commented
*[`src/SayMore/UI/ProjectWindow/ProjectWindow.cs` line 222 at r2](https://reviewable.io/reviews/sillsdev/saymore/189#-OIBfC8ZAVVl492awWaX:-OICkQKS7i-vmgL8I2of:bb6un1j) ([raw file](https://github.com/sillsdev/saymore/blob/44a06c5d21fbf50ec16f0f5ac0862423868db927/src/SayMore/UI/ProjectWindow/ProjectWindow.cs#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As we discussed, rsyncing the appcast file to the same directory as the installers may be the best option for now.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2025-02-03 22:19 UTC, merged