Updated most libraries to latest versions
sillsdev/saymore pull request #193
Opened 2024-10-28 15:38 UTC by tombogle

This especially addresses some issues with archiving as well as a vulnerability in System.Text.Json

2024-10-29 04:54 UTC, tombogle commented
I believe all the coding changes are done. Still a draft, pending release of libpalaso, so we can update to use an official release version.

2024-11-04 22:27 UTC, tombogle commented
*[`src/SayMore/UI/ComponentEditors/ContributorsEditor.cs` line 68 at r2](https://reviewable.io/reviews/sillsdev/saymore/193#-OAO-WLhD5Reo6eHBp01:-OAtHRo-CHQcnpj6jE3R:b2c4sw2) ([raw file](https://github.com/sillsdev/saymore/blob/39c559b8bc728c0ee2f94ad3be69be2ff3936457/src/SayMore/UI/ComponentEditors/ContributorsEditor.cs#L68)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Was this removal of a null check supposed to get an elvis operator?
</blockquote></details>

No, because it already cannot be null. It is used several lines about with no null check.


<!-- Sent from Reviewable.io -->

2024-11-04 22:35 UTC, andrew-polk reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`src/SayMore/UI/ComponentEditors/ContributorsEditor.cs` line 68 at r2](https://reviewable.io/reviews/sillsdev/saymore/193#-OAO-WLhD5Reo6eHBp01:-OAtJGOXDJM57a6cFnmK:bfx5ix7) ([raw file](https://github.com/sillsdev/saymore/blob/39c559b8bc728c0ee2f94ad3be69be2ff3936457/src/SayMore/UI/ComponentEditors/ContributorsEditor.cs#L68)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

No, because it already cannot be null. It is used several lines about with no null check.
</blockquote></details>

Hm. Thought I had looked for that, but apparently I missed it.


<!-- Sent from Reviewable.io -->

2025-01-08 20:21 UTC, tombogle commented
Note to self: Need to add System.IO.Compression.dll to the Installer.

2025-01-14 19:03 UTC, andrew-polk reviewed
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: all files reviewed, 4 unresolved discussions (waiting on @tombogle)

___
*[`src/SayMore/Model/Project.cs` line 791 at r3](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaBFnj8-OcLI7kUYms:-OGaBFnj8-OcLI7kUYmt:b-g0b76h) ([raw file](https://github.com/sillsdev/saymore/blob/3da102254b7a13109cce95e48c74156bc8937058/src/SayMore/Model/Project.cs#L791)):*
> ```Smalltalk
> 		public IEnumerable<string> GetSessionFilesToArchive(Type typeOfArchive, CancellationToken cancellationToken)
> 		{
> 			// RAMP packages must not be compressed or RAMP can't read them.
> ```

I think this comment goes with the subsequent line.
___
*[`src/SayMore/Model/Project.cs` line 792 at r3](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaBSvq-uwMtESeKJYB:-OGaBSvq-uwMtESeKJYC:bq4nqvf) ([raw file](https://github.com/sillsdev/saymore/blob/3da102254b7a13109cce95e48c74156bc8937058/src/SayMore/Model/Project.cs#L792)):*
> ```Smalltalk
> 		{
> 			// RAMP packages must not be compressed or RAMP can't read them.
> 			var tempZipFilePath = ChangeExtension(GetTempFileName(), "zip");
> ```

Is it necessary to change the extension?
I'm sure it doesn't hurt anything other than an extra IO call.
___
*[`src/SayMoreTests/packages.config` line 47 at r3](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaBjg09DIUe3xnYQYK:-OGaBjg09DIUe3xnYQYL:b-928n8d) ([raw file](https://github.com/sillsdev/saymore/blob/3da102254b7a13109cce95e48c74156bc8937058/src/SayMoreTests/packages.config#L47)):*
> ```XML
>   <package id="System.Drawing.Common" version="6.0.0" targetFramework="net462" />
>   <package id="System.IO.Compression" version="4.3.0" targetFramework="net462" />
>   <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net462" />
> ```

Based on the fact that you didn't have to make any related code changes in the Tests project, I'm guessing this isn't actually a dependency?
___
*[`src/SayMore/packages.config` line 9 at r1](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaAw0pAd-3mh2oBLmT:-OGaAw0pAd-3mh2oBLmU:b48ajax) ([raw file](https://github.com/sillsdev/saymore/blob/74307cfdf3037f82da5f5b373108d1823476476e/src/SayMore/packages.config#L9)):*
> ```XML
>   <package id="Coroutine.NET" version="1.4.0" targetFramework="net462" />
>   <package id="DialogAdapters.Gtk2" version="0.1.11" targetFramework="net462" />
>   <package id="DotNetZip" version="1.16.0" targetFramework="net462" />
> ```

Just verifying this isn't needed as a dependency of libpalaso?


<!-- Sent from Reviewable.io -->

2025-01-17 17:25 UTC, tombogle reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/SayMore/packages.config` line 9 at r1](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaAw0pAd-3mh2oBLmT:-OGkuaFKB8Qfnr9yqkip:bx4ve1w) ([raw file](https://github.com/sillsdev/saymore/blob/74307cfdf3037f82da5f5b373108d1823476476e/src/SayMore/packages.config#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Just verifying this isn't needed as a dependency of libpalaso?
</blockquote></details>

Not anymore. (It is still used in the current released version of ParatextData, so programs that depend on that have to live with it a little longer.)
___
*[`src/SayMore/Model/Project.cs` line 791 at r3](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaBFnj8-OcLI7kUYms:-OGpG19Z1gL1Z79GAkqL:b-896fix) ([raw file](https://github.com/sillsdev/saymore/blob/3da102254b7a13109cce95e48c74156bc8937058/src/SayMore/Model/Project.cs#L791)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this comment goes with the subsequent line.
</blockquote></details>

Done.
___
*[`src/SayMore/Model/Project.cs` line 792 at r3](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaBSvq-uwMtESeKJYB:-OGpGZNe9sMYXC1W9ce5:bfvyg6p) ([raw file](https://github.com/sillsdev/saymore/blob/3da102254b7a13109cce95e48c74156bc8937058/src/SayMore/Model/Project.cs#L792)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it necessary to change the extension?
I'm sure it doesn't hurt anything other than an extra IO call.
</blockquote></details>

GetTempFileName actually creates the file, so we either have to change the extension or delete the file. CreateFromDirectory doesn't have a param to tell it to overwrite it. Maybe deleting it would be better, as we wouldn't leave a junk temp file laying around, but Windows takes care of cleaning them up.
___
*[`src/SayMoreTests/packages.config` line 47 at r3](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaBjg09DIUe3xnYQYK:-OGpI2slDgUm_blavZq8:bgrmdve) ([raw file](https://github.com/sillsdev/saymore/blob/3da102254b7a13109cce95e48c74156bc8937058/src/SayMoreTests/packages.config#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Based on the fact that you didn't have to make any related code changes in the Tests project, I'm guessing this isn't actually a dependency?
</blockquote></details>

"Unable to uninstall 'System.IO.Compression.ZipFile.4.3.0' because 'SIL.Archiving.15.0.0' depends on it."


<!-- Sent from Reviewable.io -->

2025-01-17 18:57 UTC, andrew-polk reviewed
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2025-01-17 19:18 UTC, andrew-polk approved these changes
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/SayMore/Model/Project.cs` line 792 at r3](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaBSvq-uwMtESeKJYB:-OGpgh0QAlqxDpEp8z7u:bw2uj) ([raw file](https://github.com/sillsdev/saymore/blob/3da102254b7a13109cce95e48c74156bc8937058/src/SayMore/Model/Project.cs#L792)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

GetTempFileName actually creates the file, so we either have to change the extension or delete the file. CreateFromDirectory doesn't have a param to tell it to overwrite it. Maybe deleting it would be better, as we wouldn't leave a junk temp file laying around, but Windows takes care of cleaning them up.
</blockquote></details>

I wasn't sure you had understood my comment based on your response, but you changed the code the way I would have.
However, now you've changed it back, so I'll explain.

You're going to move the file to be named with .zip in the end, so it doesn't matter what the extension is in the meantime, right? Or does the zip library require that it is working with a file with the .zip extension?


<!-- Sent from Reviewable.io -->

2025-01-17 21:56 UTC, andrew-polk approved these changes
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2025-01-17 22:01 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2025-01-21 17:27 UTC, andrew-polk reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2025-01-21 21:56 UTC, andrew-polk requested changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/SayMore/Model/Project.cs` line 792 at r3](https://reviewable.io/reviews/sillsdev/saymore/193#-OGaBSvq-uwMtESeKJYB:-OH9q4Ka5dqsBSlFO2rW:bmw49lt) ([raw file](https://github.com/sillsdev/saymore/blob/3da102254b7a13109cce95e48c74156bc8937058/src/SayMore/Model/Project.cs#L792)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I did understand. I changed it based on my understanding. Then I changed it back because it failed. My response explains why it failed, and therefore why I left it as it was. The zip library does NOT care what the extension is. But it does care that that file not exist. So I either need to delete the temp file or rename it. Technically neither is 100% safe because there's always the infinitesimally small chance that the deleted file could be recreated or that a zip file might exist with the same name as the temp file. But it's pretty unlikely.
</blockquote></details>

Got it. Thanks for re-explaining.
___
*[`src/SayMore/ApplicationContainer.cs` line 209 at r10](https://reviewable.io/reviews/sillsdev/saymore/193#-OH9qyt1-f0G8MrToX-Q:-OH9qyt1-f0G8MrToX-R:bv7nnm6) ([raw file](https://github.com/sillsdev/saymore/blob/9a5d6484059328d44179af8395e5b436ca31bf98/src/SayMore/ApplicationContainer.cs#L209)):*
> ```Smalltalk
> 			get
> 			{
> 				// In production, this is super simple. It's merely Application.ProductVersion.
> ```

I think this would be more clear as
// In production, this would be super simple: Application.ProductVersion.


But if you want to shortcut the extra logic, I think you can do

if (Assembly.GetEntryAssembly() != null)
  return Application.ProductVersion;


<!-- Sent from Reviewable.io -->

2025-01-21 23:11 UTC, andrew-polk approved these changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/saymore/193)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tombogle)



<!-- Sent from Reviewable.io -->

2025-01-22 13:05 UTC, merged